/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';


import {
  IConfig,
} from './components/models/config.interface';


export namespace Components {

  interface WwTabSelection {
    'config': IConfig;
    'initiallySelectedTab': string;
  }
  interface WwTabSelectionAttributes extends StencilHTMLAttributes {
    'config'?: IConfig;
    'initiallySelectedTab'?: string;
    'onTabClicked'?: (event: CustomEvent) => void;
  }
}

declare global {
  interface StencilElementInterfaces {
    'WwTabSelection': Components.WwTabSelection;
  }

  interface StencilIntrinsicElements {
    'ww-tab-selection': Components.WwTabSelectionAttributes;
  }


  interface HTMLWwTabSelectionElement extends Components.WwTabSelection, HTMLStencilElement {}
  var HTMLWwTabSelectionElement: {
    prototype: HTMLWwTabSelectionElement;
    new (): HTMLWwTabSelectionElement;
  };

  interface HTMLElementTagNameMap {
    'ww-tab-selection': HTMLWwTabSelectionElement
  }

  interface ElementTagNameMap {
    'ww-tab-selection': HTMLWwTabSelectionElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
